name: sentry

on:
    push

jobs:
    run-deploy-tracking:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}            
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN}}
              with:
                environment: 'production'
